// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApDGKWthrEmtG0ukM9y0wQyJy935CGRT0',
    appId: '1:918157424611:web:489ab223b228d0387f12d6',
    messagingSenderId: '918157424611',
    projectId: 'coursia-100c0',
    authDomain: 'coursia-100c0.firebaseapp.com',
    storageBucket: 'coursia-100c0.appspot.com',
    measurementId: 'G-6ZW299LJ1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD185AFvVaqmTifKI2TzcHYaUMdWXVaVmI',
    appId: '1:918157424611:android:fba1711cdb8a92be7f12d6',
    messagingSenderId: '918157424611',
    projectId: 'coursia-100c0',
    storageBucket: 'coursia-100c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTBZqsHCTVrZWqt7FDljc1cNQoF6nR-5I',
    appId: '1:918157424611:ios:1669bb37fecc399f7f12d6',
    messagingSenderId: '918157424611',
    projectId: 'coursia-100c0',
    storageBucket: 'coursia-100c0.appspot.com',
    iosClientId: '918157424611-u69knl6n04k423efl156goq7218u6rdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.coursia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTBZqsHCTVrZWqt7FDljc1cNQoF6nR-5I',
    appId: '1:918157424611:ios:1669bb37fecc399f7f12d6',
    messagingSenderId: '918157424611',
    projectId: 'coursia-100c0',
    storageBucket: 'coursia-100c0.appspot.com',
    iosClientId: '918157424611-u69knl6n04k423efl156goq7218u6rdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.coursia',
  );
}
